In [25]:
from collections import Counter
import numpy as np
import pandas as pd
import math
import re

In [4]:
lat = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

In [5]:
kir = ['а', 'б', 'в', 'г', 'д', 'е', 'ё', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 
       'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я']

In [6]:
arm = ['ա', 'բ', 'գ', 'դ', 'ե', 'զ', 'է', 'ը', 'թ', 'ժ', 'ի', 'լ', 'խ', 
       'ծ', 'կ', 'հ', 'ձ', 'ղ', 'ճ', 'մ', 'յ', 'ն', 'շ', 'ո', 'չ', 'պ', 
       'ջ', 'ռ', 'ս', 'վ', 'տ', 'ր', 'ց', 'ւ', 'փ', 'ք', 'և', 'օ', 'ֆ']

In [7]:
#функция, принимающая на вход excel-file и возвращающая словарь со значениями частот для английского,
#русского и армянскго языков
def freq_dicts_function(file_name, sheet):
    df = pd.read_excel(io=file_name, sheet_name=sheet)
    let = df['let'].values.tolist()
    freq = df['freq'].values.tolist()
    return dict(zip(let, freq))

In [1]:
#freq_dicts_function("D:\\KATE\\EDUCATION\\MAGA\\HSE\\կուռսաչիկ\\корпусы\\armenian.xlsx", 'Лист1')

In [9]:
aa = freq_dicts_function("D:\\KATE\\EDUCATION\\MAGA\\HSE\\կուռսաչիկ\\корпусы\\russian.xlsx", 'Лист1')
print(aa)
aaa = list(aa.values())
print(aaa)

{'а': 0.07998, 'б': 0.01592, 'в': 0.04533, 'г': 0.01687, 'д': 0.02977, 'е': 0.08483, 'ё': 0.00013, 'ж': 0.0094, 'з': 0.01641, 'и': 0.07367, 'й': 0.01208, 'к': 0.03486, 'л': 0.04343, 'м': 0.03203, 'н': 0.067, 'о': 0.10983, 'п': 0.02804, 'р': 0.04746, 'с': 0.05473, 'т': 0.06318, 'у': 0.02615, 'ф': 0.00267, 'х': 0.00966, 'ц': 0.00486, 'ч': 0.0145, 'ш': 0.00718, 'щ': 0.00361, 'ъ': 0.00037, 'ы': 0.01898, 'ь': 0.01735, 'э': 0.00331, 'ю': 0.00639, 'я': 0.02001}
[0.07998, 0.01592, 0.04533, 0.01687, 0.02977, 0.08483, 0.00013, 0.0094, 0.01641, 0.07367, 0.01208, 0.03486, 0.04343, 0.03203, 0.067, 0.10983, 0.02804, 0.04746, 0.05473, 0.06318, 0.02615, 0.00267, 0.00966, 0.00486, 0.0145, 0.00718, 0.00361, 0.00037, 0.01898, 0.01735, 0.00331, 0.00639, 0.02001]


In [10]:
#freq_dicts_function("D:\\KATE\\EDUCATION\\MAGA\\HSE\\կուռսաչիկ\\корпусы\\english.xlsx", 'Лист1')

In [29]:
layouts = {'lat': set(lat),
           'kir': set(kir),
           'arm': set(arm)}
def get_layout(post, layouts):
    counter = {lang: 0 for lang in layouts}
    for char in post:
        for lang, layout in layouts.items():
            if char in layout:
                counter[lang] += 1
    return max(counter, key = lambda lang: counter[lang])

In [37]:
get_layout(" пра գյլդյսլֆ", layouts)

'arm'

In [41]:
# функция, принимающая на вход строку, и определяющая раскладку, на которой написана данная строка.
def get_layout(post):
    let_dict = Counter()
    for element in post:
        x = Counter(element.lower())
        let_dict = let_dict + x
    num_of_lat=0
    num_of_kir=0
    num_of_arm=0
    for key in let_dict.keys():
        if key in lat:
            num_of_lat = num_of_lat + let_dict[key]
        if key in kir:
            num_of_kir = num_of_kir + let_dict[key]
        if key in arm:
            num_of_arm = num_of_arm + let_dict[key]
    if num_of_lat > num_of_arm and num_of_lat > num_of_kir:
        result = "lat_layout"
    if num_of_arm > num_of_lat and num_of_arm > num_of_kir:
        result = "arm_layout"
    if num_of_kir > num_of_arm and num_of_kir > num_of_lat:
        result = "kir_layout"
    return result

In [27]:
get_layout("ghdlsgjdksfjdjrowytnvxnbv прадыиээц мрешж мралыжвра գյլդյսլֆ")

'lat_layout'

In [13]:
#функция,считающая относительные частоты употребления англ. букв при написании на армянском языке (по собранному корпусу)
def arm_lat_freq(corp_file):
    with open(corp_file, encoding='utf8') as v:
        corpus = [(string.rstrip()) for string in v if string.rstrip()]
    count_dict = Counter()
    for element in corpus:
        x = Counter(element.lower())
        count_dict = count_dict + x
    lat_dict = dict.fromkeys(lat, 0) #пустой словарь, ключи - буквы латиницы, значения - нули
    for letter in count_dict:
        if letter in lat_dict:
            lat_dict[letter] = count_dict[letter]
    all_lat = sum(lat_dict.values())
    list_of_lat = list(lat_dict.values())
    freq_lat = np.array(list_of_lat)/all_lat
    return freq_lat

In [38]:
arm_lat_freq(corp_file="D:\\KATE\\EDUCATION\\MAGA\\HSE\\կուռսաչիկ\\корпусы\\arm.txt")

array([0.14660091, 0.01025046, 0.03800406, 0.02059762, 0.08722561,
       0.00077362, 0.01305483, 0.04380621, 0.05831158, 0.00686587,
       0.03220191, 0.02021081, 0.0474809 , 0.08751571, 0.03906779,
       0.01382845, 0.02011411, 0.08422783, 0.03529639, 0.04467653,
       0.04496664, 0.03384586, 0.00116043, 0.01905038, 0.03471618,
       0.01614931])

In [15]:
#функция,считающая относительные частоты употребления русских букв при написании на армянском языке (по собранному корпусу)
def arm_kir_freq(corp_file):
    with open(corp_file, encoding='utf8') as v:
        corpus = [(string.rstrip()) for string in v if string.rstrip()]
    count_dict = Counter()
    for element in corpus:
        x = Counter(element.lower())
        count_dict = count_dict + x
    kir_dict = dict.fromkeys(kir, 0) #пустой словарь, ключи - буквы латиницы, значения - нули
    for letter in count_dict:
        if letter in kir_dict:
            kir_dict[letter] = count_dict[letter]
    all_kir = sum(kir_dict.values())
    list_of_kir = list(kir_dict.values())
    freq_kir = np.array(list_of_kir)/all_kir
    return freq_kir

In [39]:
arm_kir_freq(corp_file="D:\\KATE\\EDUCATION\\MAGA\\HSE\\կուռսաչիկ\\корпусы\\арм.txt")

array([1.27531044e-01, 9.28515494e-03, 3.71406198e-02, 1.02919790e-02,
       1.71160085e-02, 1.08177649e-01, 3.35608010e-04, 3.80355744e-03,
       1.15225417e-02, 7.24913301e-02, 1.34243204e-03, 4.22866092e-02,
       2.84148115e-02, 5.58227990e-02, 8.52444345e-02, 3.80355744e-02,
       1.62210538e-02, 8.75936906e-02, 5.14598948e-02, 4.68732520e-02,
       4.65376440e-02, 7.83085356e-04, 1.99127419e-02, 3.60219264e-02,
       2.11433046e-02, 9.62076295e-03, 1.11869337e-04, 0.00000000e+00,
       4.47477346e-04, 2.23738673e-04, 3.02047209e-03, 2.90860275e-03,
       8.27833091e-03])

In [42]:
#функция, на съедение которой отправится прибывший пост
def post_freq(post):
    count_dict = Counter()
    x = Counter(post.lower())
    count_dict = count_dict + x
    if get_layout(post) == 'arm_layout':
        return 'Post lang - armenian, layout - armenian'
    if get_layout(post) == 'lat_layout': 
        lat_dict = dict.fromkeys(lat, 0)
        for letter in count_dict:
            if letter in lat_dict:
                lat_dict[letter] = count_dict[letter]
        list_of_lat = list(lat_dict.values())
        result =  ['lat', np.array(list_of_lat)]
    if get_layout(post) == 'kir_layout': 
        kir_dict = dict.fromkeys(kir, 0)
        for letter in count_dict:
            if letter in kir_dict:
                kir_dict[letter] = count_dict[letter]
        list_of_kir = list(kir_dict.values())
        result =  ['kir', np.array(list_of_kir)]
    return result


In [43]:
a = post_freq("ghdlsgjdksfjdjrowytnvxnbv прадыиээц мрешж абвралыдврмралыжвра գյլդյսլֆ")
a

['kir',
 array([5, 1, 3, 0, 2, 1, 0, 2, 0, 1, 0, 0, 2, 2, 0, 0, 1, 6, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 0, 3, 0, 2, 0, 0])]

In [20]:
o=a[1]

In [24]:
np.log(o)

C:\Users\Kate Mamyan\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([1.60943791, 0.        , 1.09861229,       -inf, 0.69314718,
       0.        ,       -inf, 0.69314718,       -inf, 0.        ,
             -inf,       -inf, 0.69314718, 0.69314718,       -inf,
             -inf, 0.        , 1.79175947,       -inf,       -inf,
             -inf,       -inf,       -inf, 0.        ,       -inf,
       0.        ,       -inf,       -inf, 1.09861229,       -inf,
       0.69314718,       -inf,       -inf])